/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as contractSwapSol from "./ContractSwap.sol";
export type { contractSwapSol };
export type { Token } from "./Token";
